hide_download: true
hide_download_original: null
leftnav:
- identifier: d75f2a92-a3b5-774a-ec83-ea30ef26358f
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 0e5dff0f-5be3-3a5b-7ef4-7d4036d357e4
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: ed2d34ae-2c01-4cf8-d859-f13b63cb9854
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 00ccce44-e685-2e82-c500-168eb4144186
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 3546b380-6cf2-0f9d-3b91-d2d99580c0d1
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: 353224f8-5912-24e2-f273-59c0aa56b239
  name: Tools
  pageRef: /pages/tools
  weight: 60
